openapi: 3.1.0

info:
  title: Kai Security Vulerabilities Scan
  version: v1

servers:
  - url: http://localhost:8080/api/v1

paths:
  /scan:
    $ref: './resources/scan.yaml#/FetchVulnerabilities'
  /query:
    $ref: './resources/query.yaml#/SearchVulnerabilities'
